export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    ADD_CART: "ADD_CART",
    REMOVE_CART: "REMOVE_CART",
    INCREMENT_CART: "INCREMENT_CART",
    DECREMENT_CART: "DECREMENT_CART",
}